### ISSUE TITLE
Payload capacity of Open Manipulator

### ISSUE THREAD

**Issue by MONICA-PALLA** [ROBOTIS-GIT/open_manipulator#98]
May I know the payload which an Open Manipulator made of XL430 servos is capable of carrying?

Thank you,
Monica, P.

**Comment by gpwhd07** [comment]
Hi, @MONICA-PALLA 

We do not officially support the OpenManipulator with XL430 because of the low payload.
We assume that its payload will be less than 50g.

Thanks

**Comment by MONICA-PALLA** [comment]
Thank you for your reply.

Regards,
Monica, P.

**Comment by zlatinovStefan** [comment]
What about a combination of XM430 and XL430. Is it okay to replace XM430 with XL430 for the gripper or the waist?

**Comment by gpwhd07** [comment]
Hi, @zlatinovStefan 

We haven't measured the payload with that system, but that might be possible. I think you can replace `first` and `fourth` XM430 to XL430. 
The gripper dynamixel have to use current based position control mode but XL430s are not provided that mode, so that you need to use XM430 for the gripper dynamixel.
